{{- if .Values.kedaConfig.enabled }}
apiVersion: kedaConfig/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-app-chart.fullname" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "my-app-chart.fullname" . }}
  minReplicas: {{ .Values.kedaConfig.minReplicas }}
  maxReplicas: {{ .Values.kedaConfig.maxReplicas }}
  metrics:
    {{- if .Values.kedaConfig.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.kedaConfig.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.kedaConfig.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.kedaConfig.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
