replicaCount: 1 # This will be overridden by minReplicas if kedaConfig is enabled

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest" # Overrides with .Chart.AppVersion if not set

service:
  type: NodePort # Change to ClusterIP or LoadBalancer as needed
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling: # This refers to the template 'templates/hpa.yaml'
  enabled: false # <--- CRITICAL: SET THIS TO FALSE

kedaConfig:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metricType: cpu # Default, will be overridden
  metricValue: 50 # Default, will be overridden
  eventSourceConfig: {} # Default, will be overridden

serviceAccount:
  create: true
  automount: true # <--- THIS LINE
  # You can specify a name if you want, otherwise it uses the chart's full name
  # name: "your-custom-sa-name"

ingress:
  enabled: false # Set to 'true' if you actually plan to configure Ingress
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local